#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Binding.Android.Resource", IsApplication=true)]

namespace Binding.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MugenMvvmToolkit.Resource.Attribute.ActionBarTemplate = global::Binding.Android.Resource.Attribute.ActionBarTemplate;
			global::MugenMvvmToolkit.Resource.Attribute.Bind = global::Binding.Android.Resource.Attribute.Bind;
			global::MugenMvvmToolkit.Resource.Attribute.Bindings = global::Binding.Android.Resource.Attribute.Bindings;
			global::MugenMvvmToolkit.Resource.Attribute.ContentTemplate = global::Binding.Android.Resource.Attribute.ContentTemplate;
			global::MugenMvvmToolkit.Resource.Attribute.DropDownItemTemplate = global::Binding.Android.Resource.Attribute.DropDownItemTemplate;
			global::MugenMvvmToolkit.Resource.Attribute.ItemTemplate = global::Binding.Android.Resource.Attribute.ItemTemplate;
			global::MugenMvvmToolkit.Resource.Attribute.MenuTemplate = global::Binding.Android.Resource.Attribute.MenuTemplate;
			global::MugenMvvmToolkit.Resource.Attribute.PlacementTargetPath = global::Binding.Android.Resource.Attribute.PlacementTargetPath;
			global::MugenMvvmToolkit.Resource.Attribute.PopupMenuEvent = global::Binding.Android.Resource.Attribute.PopupMenuEvent;
			global::MugenMvvmToolkit.Resource.Attribute.PopupMenuTemplate = global::Binding.Android.Resource.Attribute.PopupMenuTemplate;
			global::MugenMvvmToolkit.Resource.Attribute.TabContentId = global::Binding.Android.Resource.Attribute.TabContentId;
			global::MugenMvvmToolkit.Resource.Id.AttachedProperties = global::Binding.Android.Resource.Id.AttachedProperties;
			global::MugenMvvmToolkit.Resource.Id.ListenParentChange = global::Binding.Android.Resource.Id.ListenParentChange;
			global::MugenMvvmToolkit.Resource.Id.OptionsMenu = global::Binding.Android.Resource.Id.OptionsMenu;
			global::MugenMvvmToolkit.Resource.Styleable.ActionBar = global::Binding.Android.Resource.Styleable.ActionBar;
			global::MugenMvvmToolkit.Resource.Styleable.ActionBar_ActionBarTemplate = global::Binding.Android.Resource.Styleable.ActionBar_ActionBarTemplate;
			global::MugenMvvmToolkit.Resource.Styleable.ActionBar_TabContentId = global::Binding.Android.Resource.Styleable.ActionBar_TabContentId;
			global::MugenMvvmToolkit.Resource.Styleable.Binding = global::Binding.Android.Resource.Styleable.Binding;
			global::MugenMvvmToolkit.Resource.Styleable.Binding_Bind = global::Binding.Android.Resource.Styleable.Binding_Bind;
			global::MugenMvvmToolkit.Resource.Styleable.Binding_Bindings = global::Binding.Android.Resource.Styleable.Binding_Bindings;
			global::MugenMvvmToolkit.Resource.Styleable.Control = global::Binding.Android.Resource.Styleable.Control;
			global::MugenMvvmToolkit.Resource.Styleable.Control_ContentTemplate = global::Binding.Android.Resource.Styleable.Control_ContentTemplate;
			global::MugenMvvmToolkit.Resource.Styleable.ItemsControl = global::Binding.Android.Resource.Styleable.ItemsControl;
			global::MugenMvvmToolkit.Resource.Styleable.ItemsControl_DropDownItemTemplate = global::Binding.Android.Resource.Styleable.ItemsControl_DropDownItemTemplate;
			global::MugenMvvmToolkit.Resource.Styleable.ItemsControl_ItemTemplate = global::Binding.Android.Resource.Styleable.ItemsControl_ItemTemplate;
			global::MugenMvvmToolkit.Resource.Styleable.Menu = global::Binding.Android.Resource.Styleable.Menu;
			global::MugenMvvmToolkit.Resource.Styleable.Menu_MenuTemplate = global::Binding.Android.Resource.Styleable.Menu_MenuTemplate;
			global::MugenMvvmToolkit.Resource.Styleable.Menu_PlacementTargetPath = global::Binding.Android.Resource.Styleable.Menu_PlacementTargetPath;
			global::MugenMvvmToolkit.Resource.Styleable.Menu_PopupMenuEvent = global::Binding.Android.Resource.Styleable.Menu_PopupMenuEvent;
			global::MugenMvvmToolkit.Resource.Styleable.Menu_PopupMenuTemplate = global::Binding.Android.Resource.Styleable.Menu_PopupMenuTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public const int ActionBarTemplate = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int Bind = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int Bindings = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int ContentTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int DropDownItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int ItemTemplate = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int MenuTemplate = 2130771973;
			
			// aapt resource value: 0x7f010008
			public const int PlacementTargetPath = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int PopupMenuEvent = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int PopupMenuTemplate = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int TabContentId = 2130771978;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040002
			public const int AttachedProperties = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int IterationsText = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int ListenParentChange = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int MugenExpTextView = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int MugenTextView = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int NoBindingTextView = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int OptionsMenu = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int StartButton = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int seekBar = 2130968584;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int _ButtonTemplate = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int _ListViewTemplate = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AttachedMemberView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int BindingExpressionView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int BindingModeView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int BindingResourcesView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int BindingValidationView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int CollectionBindingView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int CommandBindingView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int DynamicObjectView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int LocalizableView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Main = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int PerformanceView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int RelativeBindingView = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int addlistitemmenu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ActionBar = new int[] {
					2130771977,
					2130771978};
			
			// aapt resource value: 0
			public const int ActionBar_ActionBarTemplate = 0;
			
			// aapt resource value: 1
			public const int ActionBar_TabContentId = 1;
			
			public static int[] Binding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int Binding_Bind = 0;
			
			// aapt resource value: 1
			public const int Binding_Bindings = 1;
			
			public static int[] Control = new int[] {
					2130771972};
			
			// aapt resource value: 0
			public const int Control_ContentTemplate = 0;
			
			public static int[] ItemsControl = new int[] {
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int ItemsControl_DropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int ItemsControl_ItemTemplate = 0;
			
			public static int[] Menu = new int[] {
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int Menu_MenuTemplate = 0;
			
			// aapt resource value: 3
			public const int Menu_PlacementTargetPath = 3;
			
			// aapt resource value: 2
			public const int Menu_PopupMenuEvent = 2;
			
			// aapt resource value: 1
			public const int Menu_PopupMenuTemplate = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
