#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ApiExamples.Resource", IsApplication=true)]

namespace ApiExamples
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MugenMvvmToolkit.Resource.Attribute.ActionBarTemplate = global::ApiExamples.Resource.Attribute.ActionBarTemplate;
			global::MugenMvvmToolkit.Resource.Attribute.Bind = global::ApiExamples.Resource.Attribute.Bind;
			global::MugenMvvmToolkit.Resource.Attribute.Bindings = global::ApiExamples.Resource.Attribute.Bindings;
			global::MugenMvvmToolkit.Resource.Attribute.ContentTemplate = global::ApiExamples.Resource.Attribute.ContentTemplate;
			global::MugenMvvmToolkit.Resource.Attribute.DropDownItemTemplate = global::ApiExamples.Resource.Attribute.DropDownItemTemplate;
			global::MugenMvvmToolkit.Resource.Attribute.ItemTemplate = global::ApiExamples.Resource.Attribute.ItemTemplate;
			global::MugenMvvmToolkit.Resource.Attribute.MenuTemplate = global::ApiExamples.Resource.Attribute.MenuTemplate;
			global::MugenMvvmToolkit.Resource.Attribute.PlacementTargetPath = global::ApiExamples.Resource.Attribute.PlacementTargetPath;
			global::MugenMvvmToolkit.Resource.Attribute.PopupMenuEvent = global::ApiExamples.Resource.Attribute.PopupMenuEvent;
			global::MugenMvvmToolkit.Resource.Attribute.PopupMenuTemplate = global::ApiExamples.Resource.Attribute.PopupMenuTemplate;
			global::MugenMvvmToolkit.Resource.Attribute.TabContentId = global::ApiExamples.Resource.Attribute.TabContentId;
			global::MugenMvvmToolkit.Resource.Id.AttachedProperties = global::ApiExamples.Resource.Id.AttachedProperties;
			global::MugenMvvmToolkit.Resource.Id.ListenParentChange = global::ApiExamples.Resource.Id.ListenParentChange;
			global::MugenMvvmToolkit.Resource.Id.OptionsMenu = global::ApiExamples.Resource.Id.OptionsMenu;
			global::MugenMvvmToolkit.Resource.Styleable.ActionBar = global::ApiExamples.Resource.Styleable.ActionBar;
			global::MugenMvvmToolkit.Resource.Styleable.ActionBar_ActionBarTemplate = global::ApiExamples.Resource.Styleable.ActionBar_ActionBarTemplate;
			global::MugenMvvmToolkit.Resource.Styleable.ActionBar_TabContentId = global::ApiExamples.Resource.Styleable.ActionBar_TabContentId;
			global::MugenMvvmToolkit.Resource.Styleable.Binding = global::ApiExamples.Resource.Styleable.Binding;
			global::MugenMvvmToolkit.Resource.Styleable.Binding_Bind = global::ApiExamples.Resource.Styleable.Binding_Bind;
			global::MugenMvvmToolkit.Resource.Styleable.Binding_Bindings = global::ApiExamples.Resource.Styleable.Binding_Bindings;
			global::MugenMvvmToolkit.Resource.Styleable.Control = global::ApiExamples.Resource.Styleable.Control;
			global::MugenMvvmToolkit.Resource.Styleable.Control_ContentTemplate = global::ApiExamples.Resource.Styleable.Control_ContentTemplate;
			global::MugenMvvmToolkit.Resource.Styleable.ItemsControl = global::ApiExamples.Resource.Styleable.ItemsControl;
			global::MugenMvvmToolkit.Resource.Styleable.ItemsControl_DropDownItemTemplate = global::ApiExamples.Resource.Styleable.ItemsControl_DropDownItemTemplate;
			global::MugenMvvmToolkit.Resource.Styleable.ItemsControl_ItemTemplate = global::ApiExamples.Resource.Styleable.ItemsControl_ItemTemplate;
			global::MugenMvvmToolkit.Resource.Styleable.Menu = global::ApiExamples.Resource.Styleable.Menu;
			global::MugenMvvmToolkit.Resource.Styleable.Menu_MenuTemplate = global::ApiExamples.Resource.Styleable.Menu_MenuTemplate;
			global::MugenMvvmToolkit.Resource.Styleable.Menu_PlacementTargetPath = global::ApiExamples.Resource.Styleable.Menu_PlacementTargetPath;
			global::MugenMvvmToolkit.Resource.Styleable.Menu_PopupMenuEvent = global::ApiExamples.Resource.Styleable.Menu_PopupMenuEvent;
			global::MugenMvvmToolkit.Resource.Styleable.Menu_PopupMenuTemplate = global::ApiExamples.Resource.Styleable.Menu_PopupMenuTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010014
			public const int ActionBarTemplate = 2130771988;
			
			// aapt resource value: 0x7f01000b
			public const int Bind = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int Bindings = 2130771980;
			
			// aapt resource value: 0x7f01000f
			public const int ContentTemplate = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int DropDownItemTemplate = 2130771982;
			
			// aapt resource value: 0x7f01000d
			public const int ItemTemplate = 2130771981;
			
			// aapt resource value: 0x7f010010
			public const int MenuTemplate = 2130771984;
			
			// aapt resource value: 0x7f010013
			public const int PlacementTargetPath = 2130771987;
			
			// aapt resource value: 0x7f010012
			public const int PopupMenuEvent = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int PopupMenuTemplate = 2130771985;
			
			// aapt resource value: 0x7f010015
			public const int TabContentId = 2130771989;
			
			// aapt resource value: 0x7f010000
			public const int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cardCornerRadius = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cardElevation = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cardMaxElevation = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int cardPreventCornerOverlap = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int cardUseCompatPadding = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int contentPadding = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int contentPaddingBottom = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int contentPaddingLeft = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int contentPaddingRight = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int contentPaddingTop = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int cardview_dark_background = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int cardview_light_background = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int cardview_shadow_end_color = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int cardview_shadow_start_color = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int cardview_compat_inset_shadow = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int cardview_default_elevation = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cardview_default_radius = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int AttachedProperties = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int ListenParentChange = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int OptionsMenu = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int content = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int recyclerView = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int tabContent = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int tabContentId = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int textView = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int toolbar = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int toolbarBottom = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int _ActionBarBackStackFragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int _ActionBarDynamicTab = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int _ActionBarStaticTab = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int _ButtonTemplate = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int _CardItemTemplate = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int _ContextActionBar = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int _ItemListViewTemplate = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int _ListItemTemplate = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int _ListItemTemplateInvalid = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ActionBarDynamicTabView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ActionBarMenuView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ActionBarStaticTabView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int BackStackFragmetView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int CardRecyclerView = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int ContextActionBarView = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int ItemView = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int ListDataTemplateView = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int MainView = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int PopupMenuView = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int SimpleView1 = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int SimpleView2 = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int TabHostView = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int ToolbarView = 2130903062;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int addlistitemmenu = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int addmenu = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int addremovemenu = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int contextactionbarmenu = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int dynamicmenutemplate = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int popupmenutemplate = 2131230725;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int CardView = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int CardView_Dark = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int CardView_Light = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int ToolbarTheme = 2131099651;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ActionBar = new int[] {
					2130771988,
					2130771989};
			
			// aapt resource value: 0
			public const int ActionBar_ActionBarTemplate = 0;
			
			// aapt resource value: 1
			public const int ActionBar_TabContentId = 1;
			
			public static int[] Binding = new int[] {
					2130771979,
					2130771980};
			
			// aapt resource value: 0
			public const int Binding_Bind = 0;
			
			// aapt resource value: 1
			public const int Binding_Bindings = 1;
			
			public static int[] CardView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 0
			public const int CardView_cardBackgroundColor = 0;
			
			// aapt resource value: 1
			public const int CardView_cardCornerRadius = 1;
			
			// aapt resource value: 2
			public const int CardView_cardElevation = 2;
			
			// aapt resource value: 3
			public const int CardView_cardMaxElevation = 3;
			
			// aapt resource value: 5
			public const int CardView_cardPreventCornerOverlap = 5;
			
			// aapt resource value: 4
			public const int CardView_cardUseCompatPadding = 4;
			
			// aapt resource value: 6
			public const int CardView_contentPadding = 6;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingBottom = 10;
			
			// aapt resource value: 7
			public const int CardView_contentPaddingLeft = 7;
			
			// aapt resource value: 8
			public const int CardView_contentPaddingRight = 8;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingTop = 9;
			
			public static int[] Control = new int[] {
					2130771983};
			
			// aapt resource value: 0
			public const int Control_ContentTemplate = 0;
			
			public static int[] ItemsControl = new int[] {
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int ItemsControl_DropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int ItemsControl_ItemTemplate = 0;
			
			public static int[] Menu = new int[] {
					2130771984,
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 0
			public const int Menu_MenuTemplate = 0;
			
			// aapt resource value: 3
			public const int Menu_PlacementTargetPath = 3;
			
			// aapt resource value: 2
			public const int Menu_PopupMenuEvent = 2;
			
			// aapt resource value: 1
			public const int Menu_PopupMenuTemplate = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
