#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ApiExamples.Resource", IsApplication=true)]

namespace ApiExamples
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MugenMvvmToolkit.Android.Resource.Attribute.ActionBarTemplate = global::ApiExamples.Resource.Attribute.ActionBarTemplate;
			global::MugenMvvmToolkit.Android.Resource.Attribute.Bind = global::ApiExamples.Resource.Attribute.Bind;
			global::MugenMvvmToolkit.Android.Resource.Attribute.ContentTemplate = global::ApiExamples.Resource.Attribute.ContentTemplate;
			global::MugenMvvmToolkit.Android.Resource.Attribute.DropDownItemTemplate = global::ApiExamples.Resource.Attribute.DropDownItemTemplate;
			global::MugenMvvmToolkit.Android.Resource.Attribute.ItemTemplate = global::ApiExamples.Resource.Attribute.ItemTemplate;
			global::MugenMvvmToolkit.Android.Resource.Attribute.MenuTemplate = global::ApiExamples.Resource.Attribute.MenuTemplate;
			global::MugenMvvmToolkit.Android.Resource.Attribute.PlacementTargetPath = global::ApiExamples.Resource.Attribute.PlacementTargetPath;
			global::MugenMvvmToolkit.Android.Resource.Attribute.PopupMenuEvent = global::ApiExamples.Resource.Attribute.PopupMenuEvent;
			global::MugenMvvmToolkit.Android.Resource.Attribute.PopupMenuTemplate = global::ApiExamples.Resource.Attribute.PopupMenuTemplate;
			global::MugenMvvmToolkit.Android.Resource.Attribute.TabContentId = global::ApiExamples.Resource.Attribute.TabContentId;
			global::MugenMvvmToolkit.Android.Resource.Id.AttachedProperties = global::ApiExamples.Resource.Id.AttachedProperties;
			global::MugenMvvmToolkit.Android.Resource.Id.ListTemplateId = global::ApiExamples.Resource.Id.ListTemplateId;
			global::MugenMvvmToolkit.Android.Resource.Id.OptionsMenu = global::ApiExamples.Resource.Id.OptionsMenu;
			global::MugenMvvmToolkit.Android.Resource.String.Empty = global::ApiExamples.Resource.String.Empty;
			global::MugenMvvmToolkit.Android.Resource.Styleable.Binding = global::ApiExamples.Resource.Styleable.Binding;
			global::MugenMvvmToolkit.Android.Resource.Styleable.Binding_ActionBarTemplate = global::ApiExamples.Resource.Styleable.Binding_ActionBarTemplate;
			global::MugenMvvmToolkit.Android.Resource.Styleable.Binding_Bind = global::ApiExamples.Resource.Styleable.Binding_Bind;
			global::MugenMvvmToolkit.Android.Resource.Styleable.Binding_ContentTemplate = global::ApiExamples.Resource.Styleable.Binding_ContentTemplate;
			global::MugenMvvmToolkit.Android.Resource.Styleable.Binding_DropDownItemTemplate = global::ApiExamples.Resource.Styleable.Binding_DropDownItemTemplate;
			global::MugenMvvmToolkit.Android.Resource.Styleable.Binding_ItemTemplate = global::ApiExamples.Resource.Styleable.Binding_ItemTemplate;
			global::MugenMvvmToolkit.Android.Resource.Styleable.Binding_MenuTemplate = global::ApiExamples.Resource.Styleable.Binding_MenuTemplate;
			global::MugenMvvmToolkit.Android.Resource.Styleable.Binding_PlacementTargetPath = global::ApiExamples.Resource.Styleable.Binding_PlacementTargetPath;
			global::MugenMvvmToolkit.Android.Resource.Styleable.Binding_PopupMenuEvent = global::ApiExamples.Resource.Styleable.Binding_PopupMenuEvent;
			global::MugenMvvmToolkit.Android.Resource.Styleable.Binding_PopupMenuTemplate = global::ApiExamples.Resource.Styleable.Binding_PopupMenuTemplate;
			global::MugenMvvmToolkit.Android.Resource.Styleable.Binding_TabContentId = global::ApiExamples.Resource.Styleable.Binding_TabContentId;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010017
			public const int ActionBarTemplate = 2130771991;
			
			// aapt resource value: 0x7f01000f
			public const int Bind = 2130771983;
			
			// aapt resource value: 0x7f010012
			public const int ContentTemplate = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int DropDownItemTemplate = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int ItemTemplate = 2130771984;
			
			// aapt resource value: 0x7f010013
			public const int MenuTemplate = 2130771987;
			
			// aapt resource value: 0x7f010016
			public const int PlacementTargetPath = 2130771990;
			
			// aapt resource value: 0x7f010015
			public const int PopupMenuEvent = 2130771989;
			
			// aapt resource value: 0x7f010014
			public const int PopupMenuTemplate = 2130771988;
			
			// aapt resource value: 0x7f010018
			public const int TabContentId = 2130771992;
			
			// aapt resource value: 0x7f010004
			public const int cardBackgroundColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cardCornerRadius = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cardElevation = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cardMaxElevation = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int cardPreventCornerOverlap = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int cardUseCompatPadding = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public const int contentPadding = 2130771978;
			
			// aapt resource value: 0x7f01000e
			public const int contentPaddingBottom = 2130771982;
			
			// aapt resource value: 0x7f01000b
			public const int contentPaddingLeft = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int contentPaddingRight = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int contentPaddingTop = 2130771981;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080000
			public const int cardview_dark_background = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int cardview_light_background = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int cardview_shadow_end_color = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int cardview_shadow_start_color = 2131230723;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050003
			public const int cardview_compat_inset_shadow = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int cardview_default_elevation = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int cardview_default_radius = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int item_touch_helper_swipe_escape_max_velocity = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int item_touch_helper_swipe_escape_velocity = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int AttachedProperties = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int ListTemplateId = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int OptionsMenu = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int content = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int item_touch_helper_previous_elevation = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int recyclerView = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int tabContent = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int tabContentId = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int textView = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int toolbar = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int toolbarBottom = 2131099658;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int _ActionBarBackStackFragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int _ActionBarDynamicTab = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int _ActionBarStaticTab = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int _ButtonTemplate = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int _CardItemTemplate = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int _ContextActionBar = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int _ItemListViewTemplate = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int _ListItemTemplate = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int _ListItemTemplateInvalid = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ActionBarDynamicTabView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ActionBarMenuView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ActionBarStaticTabView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int BackStackFragmetView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int CardRecyclerView = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int ContextActionBarView = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int ItemView = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int ListDataTemplateView = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int MainView = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int PopupMenuView = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int SimpleView1 = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int SimpleView2 = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int TabHostView = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int ToolbarView = 2130903062;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int addlistitemmenu = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int addmenu = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int addremovemenu = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int contextactionbarmenu = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int dynamicmenutemplate = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int popupmenutemplate = 2131361797;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090000
			public const int Empty = 2131296256;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int Base_CardView = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int CardView = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int CardView_Dark = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int CardView_Light = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int Theme_AppCompat_NoActionBar_FullScreen = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int ToolbarTheme = 2131165188;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int pref = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int prefheaders = 2130968577;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] Binding = new int[] {
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992};
			
			// aapt resource value: 8
			public const int Binding_ActionBarTemplate = 8;
			
			// aapt resource value: 0
			public const int Binding_Bind = 0;
			
			// aapt resource value: 3
			public const int Binding_ContentTemplate = 3;
			
			// aapt resource value: 2
			public const int Binding_DropDownItemTemplate = 2;
			
			// aapt resource value: 1
			public const int Binding_ItemTemplate = 1;
			
			// aapt resource value: 4
			public const int Binding_MenuTemplate = 4;
			
			// aapt resource value: 7
			public const int Binding_PlacementTargetPath = 7;
			
			// aapt resource value: 6
			public const int Binding_PopupMenuEvent = 6;
			
			// aapt resource value: 5
			public const int Binding_PopupMenuTemplate = 5;
			
			// aapt resource value: 9
			public const int Binding_TabContentId = 9;
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
