#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Navigation.Android.Resource", IsApplication=true)]

namespace Navigation.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MugenMvvmToolkit.Android.Resource.Attribute.ActionBarTemplate = global::Navigation.Android.Resource.Attribute.ActionBarTemplate;
			global::MugenMvvmToolkit.Android.Resource.Attribute.Bind = global::Navigation.Android.Resource.Attribute.Bind;
			global::MugenMvvmToolkit.Android.Resource.Attribute.ContentTemplate = global::Navigation.Android.Resource.Attribute.ContentTemplate;
			global::MugenMvvmToolkit.Android.Resource.Attribute.DropDownItemTemplate = global::Navigation.Android.Resource.Attribute.DropDownItemTemplate;
			global::MugenMvvmToolkit.Android.Resource.Attribute.ItemTemplate = global::Navigation.Android.Resource.Attribute.ItemTemplate;
			global::MugenMvvmToolkit.Android.Resource.Attribute.MenuTemplate = global::Navigation.Android.Resource.Attribute.MenuTemplate;
			global::MugenMvvmToolkit.Android.Resource.Attribute.PlacementTargetPath = global::Navigation.Android.Resource.Attribute.PlacementTargetPath;
			global::MugenMvvmToolkit.Android.Resource.Attribute.PopupMenuEvent = global::Navigation.Android.Resource.Attribute.PopupMenuEvent;
			global::MugenMvvmToolkit.Android.Resource.Attribute.PopupMenuTemplate = global::Navigation.Android.Resource.Attribute.PopupMenuTemplate;
			global::MugenMvvmToolkit.Android.Resource.Attribute.TabContentId = global::Navigation.Android.Resource.Attribute.TabContentId;
			global::MugenMvvmToolkit.Android.Resource.Id.AttachedProperties = global::Navigation.Android.Resource.Id.AttachedProperties;
			global::MugenMvvmToolkit.Android.Resource.Id.ListTemplateId = global::Navigation.Android.Resource.Id.ListTemplateId;
			global::MugenMvvmToolkit.Android.Resource.Id.OptionsMenu = global::Navigation.Android.Resource.Id.OptionsMenu;
			global::MugenMvvmToolkit.Android.Resource.String.Empty = global::Navigation.Android.Resource.String.Empty;
			global::MugenMvvmToolkit.Android.Resource.Styleable.Binding = global::Navigation.Android.Resource.Styleable.Binding;
			global::MugenMvvmToolkit.Android.Resource.Styleable.Binding_ActionBarTemplate = global::Navigation.Android.Resource.Styleable.Binding_ActionBarTemplate;
			global::MugenMvvmToolkit.Android.Resource.Styleable.Binding_Bind = global::Navigation.Android.Resource.Styleable.Binding_Bind;
			global::MugenMvvmToolkit.Android.Resource.Styleable.Binding_ContentTemplate = global::Navigation.Android.Resource.Styleable.Binding_ContentTemplate;
			global::MugenMvvmToolkit.Android.Resource.Styleable.Binding_DropDownItemTemplate = global::Navigation.Android.Resource.Styleable.Binding_DropDownItemTemplate;
			global::MugenMvvmToolkit.Android.Resource.Styleable.Binding_ItemTemplate = global::Navigation.Android.Resource.Styleable.Binding_ItemTemplate;
			global::MugenMvvmToolkit.Android.Resource.Styleable.Binding_MenuTemplate = global::Navigation.Android.Resource.Styleable.Binding_MenuTemplate;
			global::MugenMvvmToolkit.Android.Resource.Styleable.Binding_PlacementTargetPath = global::Navigation.Android.Resource.Styleable.Binding_PlacementTargetPath;
			global::MugenMvvmToolkit.Android.Resource.Styleable.Binding_PopupMenuEvent = global::Navigation.Android.Resource.Styleable.Binding_PopupMenuEvent;
			global::MugenMvvmToolkit.Android.Resource.Styleable.Binding_PopupMenuTemplate = global::Navigation.Android.Resource.Styleable.Binding_PopupMenuTemplate;
			global::MugenMvvmToolkit.Android.Resource.Styleable.Binding_TabContentId = global::Navigation.Android.Resource.Styleable.Binding_TabContentId;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010008
			public const int ActionBarTemplate = 2130771976;
			
			// aapt resource value: 0x7f010000
			public const int Bind = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int ContentTemplate = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int DropDownItemTemplate = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int ItemTemplate = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int MenuTemplate = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int PlacementTargetPath = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int PopupMenuEvent = 2130771974;
			
			// aapt resource value: 0x7f010005
			public const int PopupMenuTemplate = 2130771973;
			
			// aapt resource value: 0x7f010009
			public const int TabContentId = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int AttachedProperties = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int ListTemplateId = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int OptionsMenu = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int placeholder = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int tabContentId = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int viewmodelplaceholder = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int _ActionBarMain = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BackStackView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FirstView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SecondView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TabTemplate = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int WrapperView = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int MainMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int Empty = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] Binding = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 8
			public const int Binding_ActionBarTemplate = 8;
			
			// aapt resource value: 0
			public const int Binding_Bind = 0;
			
			// aapt resource value: 3
			public const int Binding_ContentTemplate = 3;
			
			// aapt resource value: 2
			public const int Binding_DropDownItemTemplate = 2;
			
			// aapt resource value: 1
			public const int Binding_ItemTemplate = 1;
			
			// aapt resource value: 4
			public const int Binding_MenuTemplate = 4;
			
			// aapt resource value: 7
			public const int Binding_PlacementTargetPath = 7;
			
			// aapt resource value: 6
			public const int Binding_PopupMenuEvent = 6;
			
			// aapt resource value: 5
			public const int Binding_PopupMenuTemplate = 5;
			
			// aapt resource value: 9
			public const int Binding_TabContentId = 9;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
