#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Validation.Android.Resource", IsApplication=true)]

namespace Validation.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MugenMvvmToolkit.Resource.Attribute.ActionBarTemplate = global::Validation.Android.Resource.Attribute.ActionBarTemplate;
			global::MugenMvvmToolkit.Resource.Attribute.Bind = global::Validation.Android.Resource.Attribute.Bind;
			global::MugenMvvmToolkit.Resource.Attribute.Bindings = global::Validation.Android.Resource.Attribute.Bindings;
			global::MugenMvvmToolkit.Resource.Attribute.ContentTemplate = global::Validation.Android.Resource.Attribute.ContentTemplate;
			global::MugenMvvmToolkit.Resource.Attribute.DropDownItemTemplate = global::Validation.Android.Resource.Attribute.DropDownItemTemplate;
			global::MugenMvvmToolkit.Resource.Attribute.ItemTemplate = global::Validation.Android.Resource.Attribute.ItemTemplate;
			global::MugenMvvmToolkit.Resource.Attribute.MenuTemplate = global::Validation.Android.Resource.Attribute.MenuTemplate;
			global::MugenMvvmToolkit.Resource.Attribute.PlacementTargetPath = global::Validation.Android.Resource.Attribute.PlacementTargetPath;
			global::MugenMvvmToolkit.Resource.Attribute.PopupMenuEvent = global::Validation.Android.Resource.Attribute.PopupMenuEvent;
			global::MugenMvvmToolkit.Resource.Attribute.PopupMenuTemplate = global::Validation.Android.Resource.Attribute.PopupMenuTemplate;
			global::MugenMvvmToolkit.Resource.Attribute.TabContentId = global::Validation.Android.Resource.Attribute.TabContentId;
			global::MugenMvvmToolkit.Resource.Id.ActionBarView = global::Validation.Android.Resource.Id.ActionBarView;
			global::MugenMvvmToolkit.Resource.Id.OptionsMenu = global::Validation.Android.Resource.Id.OptionsMenu;
			global::MugenMvvmToolkit.Resource.Styleable.ActionBar = global::Validation.Android.Resource.Styleable.ActionBar;
			global::MugenMvvmToolkit.Resource.Styleable.ActionBar_ActionBarTemplate = global::Validation.Android.Resource.Styleable.ActionBar_ActionBarTemplate;
			global::MugenMvvmToolkit.Resource.Styleable.ActionBar_TabContentId = global::Validation.Android.Resource.Styleable.ActionBar_TabContentId;
			global::MugenMvvmToolkit.Resource.Styleable.Binding = global::Validation.Android.Resource.Styleable.Binding;
			global::MugenMvvmToolkit.Resource.Styleable.Binding_Bind = global::Validation.Android.Resource.Styleable.Binding_Bind;
			global::MugenMvvmToolkit.Resource.Styleable.Binding_Bindings = global::Validation.Android.Resource.Styleable.Binding_Bindings;
			global::MugenMvvmToolkit.Resource.Styleable.Control = global::Validation.Android.Resource.Styleable.Control;
			global::MugenMvvmToolkit.Resource.Styleable.Control_ContentTemplate = global::Validation.Android.Resource.Styleable.Control_ContentTemplate;
			global::MugenMvvmToolkit.Resource.Styleable.ItemsControl = global::Validation.Android.Resource.Styleable.ItemsControl;
			global::MugenMvvmToolkit.Resource.Styleable.ItemsControl_DropDownItemTemplate = global::Validation.Android.Resource.Styleable.ItemsControl_DropDownItemTemplate;
			global::MugenMvvmToolkit.Resource.Styleable.ItemsControl_ItemTemplate = global::Validation.Android.Resource.Styleable.ItemsControl_ItemTemplate;
			global::MugenMvvmToolkit.Resource.Styleable.Menu = global::Validation.Android.Resource.Styleable.Menu;
			global::MugenMvvmToolkit.Resource.Styleable.Menu_MenuTemplate = global::Validation.Android.Resource.Styleable.Menu_MenuTemplate;
			global::MugenMvvmToolkit.Resource.Styleable.Menu_PlacementTargetPath = global::Validation.Android.Resource.Styleable.Menu_PlacementTargetPath;
			global::MugenMvvmToolkit.Resource.Styleable.Menu_PopupMenuEvent = global::Validation.Android.Resource.Styleable.Menu_PopupMenuEvent;
			global::MugenMvvmToolkit.Resource.Styleable.Menu_PopupMenuTemplate = global::Validation.Android.Resource.Styleable.Menu_PopupMenuTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public const int ActionBarTemplate = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int Bind = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int Bindings = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int ContentTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int DropDownItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int ItemTemplate = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int MenuTemplate = 2130771973;
			
			// aapt resource value: 0x7f010008
			public const int PlacementTargetPath = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int PopupMenuEvent = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int PopupMenuTemplate = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int TabContentId = 2130771978;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040001
			public const int ActionBarView = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int OptionsMenu = 2130968576;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int _userlisttemplate = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dataannotationview = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int userworkspaceview = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ActionBar = new int[] {
					2130771977,
					2130771978};
			
			// aapt resource value: 0
			public const int ActionBar_ActionBarTemplate = 0;
			
			// aapt resource value: 1
			public const int ActionBar_TabContentId = 1;
			
			public static int[] Binding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int Binding_Bind = 0;
			
			// aapt resource value: 1
			public const int Binding_Bindings = 1;
			
			public static int[] Control = new int[] {
					2130771972};
			
			// aapt resource value: 0
			public const int Control_ContentTemplate = 0;
			
			public static int[] ItemsControl = new int[] {
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int ItemsControl_DropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int ItemsControl_ItemTemplate = 0;
			
			public static int[] Menu = new int[] {
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int Menu_MenuTemplate = 0;
			
			// aapt resource value: 3
			public const int Menu_PlacementTargetPath = 3;
			
			// aapt resource value: 2
			public const int Menu_PopupMenuEvent = 2;
			
			// aapt resource value: 1
			public const int Menu_PopupMenuTemplate = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
